POST /residents/7/relationship
Content-Type: application/json
Host: localhost:8080

{
  "familySerialNumber": 3,
  "familyRelationshipCode": "부"
}

###

PUT /residents/7/relationship/3
Content-Type: application/json
Host: localhost:8080

{
  "familyRelationshipCode": "모"
}

###

DELETE /residents/7/relationship/4
Host: localhost:8080